#+TITLE: My Wiki 
#+DATE: <2021-09-20 Mon>
#+AUTHOR: Salvador Guzman
#+EMAIL: guzmansalv@gmail.com
#+CATEGORY: Admin
#+LANGUAGE: en

* Hi! It's me Salvador Guzman.
  My name is *Salvador Guzman* and this is my wiki :).
 
** Introduction
*** What is this and Who am I?
   I'm a very active guy. I don't mean physically since I spent the majority of
   my day sitting on my triple-decker seat cushions. No, no. I am athletic in a
   in a more intellectual sense. I'm one of those too-smart for their own good
   type of people. This leads to the unfortunate scenario where I brainstorm
   more ideas than I know what to do with.

   This sounds like a brag but I swear it's not. In fact, it is a curse. I am
   forced for time evermore to produce half-baked ideas that I cannot possibly
   refine on my own. Why not? Well, refining ideas gets in the way of generating
   more ideas! Isn't that sad? I think it is.

   Whatever potent combination nature sought out to imbue my mental headspace
   with suffers from an abudance of prejudice of those dang loose threads. They
   just dont know when to stop. I know because it belying it is a hair trigger
   mechanism that requires very little stimulus to start chasing its own
   tail. Yes, yes; no.

   It makes for an interesting mental life but sadly can only be enjoyed at the
   expense of our flesh and blood; meaning your material life. Anyway, I would
   like my thoughts to be more than just manic intellectual daydreams I chase at
   my leisure. Within that undertaking is this.

   My personal wiki.

   I intend to write up all my thoughts here eventually in as prodigious in
   scale as possible to perfectly layout what I intended to say. It's a wiki for
   my thoughts and my own personal research. I'm using Emacs' Org-mode for all
   this fanfare to try it out :D
*** TL;DR
    My personal wiki where I write about my research.

** Area of Research
   Here are some areas of inquiry that I have pursued in my research. Most of it
   may not be intelligible to the outsider (read: person that isn't me) but it
   is stuff I wish to pursue at some point. If I write it down, that means it
   has already been polished a bit from the first time it magically appeared in
   my head.

*** My Favorite Species of Intellectual Inquiry...
   While I don't wish to pigeonhole myself, my mathematical research is my pride
   and joy. It is the field that I have suffered the most for and yielded the
   most diamonds thereof. Consider everything junk except for mathematics which
   intends to tell you a true story.

   Below is a sample of some of my thoughts in their respective disciplines.

*** Disciplines
**** Mathematics
     My attempt to build a hierarchical *tower* of iterated function. The idea
     is to construct other functions from some base function and produce a
     simple algebraic formalisms between these different iterations. Why do
     this? Because I was working on Collatz Conjecture for fun and wanted badly
     for the solution to involve iteration of some basic function that was
     faithful to the Collatz Conjecture function at positive integers. With a
     simple algebra for iterated functions I could then build a representative
     of the Collatz function, at least at positive integers, and iterate to
     successive iterate each number to their prospective terminal node. If I
     could do this sucessfully, I would be part way to a conclusive and
     definitive solution to the conjecture in question. At least that's what I
     claim 🙃

**** Computer Science
     Now follow me on this. While the concept of infinity shares affinity moreso
     to mathematics, I think it has a primary role to play in computer
     science. Consider this a particular approach to interpreting infinity,
     confined approximately to the domain of discourse in study. This means that
     the idea of infinity is general enough to find purchase within relatively
     narrow bounds of whatever line of inquiry is being followed. To illustrate
     an example, take the [[https://en.wikipedia.org/wiki/Halting_problem][Halting Problem]] as a candidate primary for the
     application of this idea of infinity. To say that, there does not exist
     such an algorithm is to say that there does not exist a finitary algorithm
     to accomplish such an endeavor. Although you may have never explicitly
     tacted on a finite dimension to that conclusive statement, that is what is
     strongly implicated. A *finitary* algorithm can be decoupled into its
     constituent *finitary* steps. That definitively exhausts purview of the
     Halting Problem statement. /However/, if there were to be *non-finitary*
     algorithms with perhaps *non-finitary* steps, they could maybe offer a
     solution. That is my application of the infinite to a particular computer
     science problem. Infinitary algorithms could solve it, whatever that
     means...

**** Language
     Unlike the young and devilishly handsome [[https://en.wikipedia.org/wiki/Ludwig_Wittgenstein][Wittgenstein]], I do not think
     language is everything. And [[https://en.wikipedia.org/wiki/Linguistic_relativity][linguistic relativity]] fails to capture the
     nature of language in practice. Whatever innate general and linguistic
     neural devices we have attending to the acquisition, comprehension and
     production of linguistic artifacts, our linguistic capacity is limited by
     said mechanisms. Our language is the beneficiary of our limitations; not
     the progenitor of the limitations. Unfortunately, discourse concerning the
     domain of discourse, in this case language, requires one be a bit of a
     pedant. The gist of my musings on language is that language is limited by
     our innate linguistic capacity to work with language. Language is not all
     that is out there, although some more introverted and literate types of
     people can be forgiven for positing as much. I once was such a type. 

**** Library Science
     I find it amusing  how library science, the discipline associated with
     organizing information in a feasible and efficient format, is not discussed
     more than it is. Yes; you can be the most prolific theoretician and produce
     prodigious quantities and volumes on whatever field of study that has
     purchased your fancy; you will for eons forward be remembered for the being
     the kind, intelligent and sensitive thinker that you truly; you will have
     all of us. But if posteriority cannot properly engage with your material do
     to your oversight of the matter of organization, you doom yourself, reader!
     Library science attempts to give feasible consolidation of the expanse of
     knowledge and make it accessible to everyone. If that is not a laudable
     goal, nothing is. 

**** Pedagogy
     Given that everyone and their maternal relatives seem to want to contribute
     theory in one shape or form or some discipline, who exactly is going to
     organize this mess? Think of it; a giant mass of papers with no obvious
     connection to one another. How exactly is this supposed to aid to material
     condition of mankind and allay their supposed privations if you can't even
     make heads or tails of the damn thing. It has always been a trite statement
     of mine that theories, and a semiotic events really, should contain their
     own pedagogy. What does mean? I don't know but I can define what the
     productive end result should be. It is the difference between a simple,
     positive theory of the world versus a simple theory of the world that
     contains within it the seeds not just to understand it but to extol
     it. Beyond that imagination fails as this is a rather incipient thought of
     mine. Maybe I will construct such a object for demonstration eventually.
 
**** Politics
     Now, you may have intuited from my name that I am Mexican. This colors my
     take on politics profoundly and provides a permeable perspective that
     encapsulates judiciously how I view politics. I do not necessarily view it
     as an abstract game played in the halls of academia but a discoursive
     reality played out millions of times in the ordinary and plain interactions
     of people. My prejudice towards abstractions in this realm of experience
     belies the inaccessibility of these lofty ideas to the mundane
     world. So what matters? Whatever system that entails should provide for the
     metabolic demands of the real people that constitute this system. Whether
     it's providing material relief in the form of social welfare or demarcating
     some economic adverserial capicity, notwithstanding the unruly social
     relations it would entail, in order to secure material propsperity, or the
     prospective pursuit thereof, people have needs. If those needs are met, the
     system is bad. No theory is necessary to conclude that.

**** Romance
     I don't want to be a sour bunch of grapes and present that as the position
     I tenaciously hold out of sheer malice. Whatever charity may prevail and
     the risk of incurring protest from the gallery or the chorus, I do not think romance as
     something necessarily demanding laconic ebullience at exhaust. Nay; one can
     say many things about it and never repeat. That I insist on muttering
     whatever trinkle of wisdom these tired bones exude, I assure you I do not
     wish to remonstrate the gaiety afforded to all of mankind by its hegemonic
     exercise. Enjoy it, is what I would offer. What midicum of insight I
     maintain must prevail is that it is a demonstrable and permissible area of
     inquiry. That is why I justifiably hold that romance can be understood to
     the deliberate exercise of rational thought. It can be conceptualized,
     studied, theorized and abetted into something mundane. And thusly do I
     inuit to do so. If that constitutes maltreatment and my mental manhandling
     of the thing a vice, then so be it. Theories often prevail in worse
     conditions and poets will found yet another impetus to migrate their
     passions. So be it.

** Any Meta-Disciplinary Themes?
   After reading my samples excepts, I hope you are no impressed! If not, I have
   failed to stimulate in you the passion that madly drives me to write in the
   first place. Maybe it will a life-long struggle then to impress others what
   my intellectual ramblings are all about.

   Either way, I hope to connect the disparate blotches of intellectual
   inquisition that I have labored under. If I had to claim there are some
   themes to my fugue-like pondering, I would say most of my creative research
   seems to consist of iterating over the same fiction that produced past
   facts. It's taking some idea that has been produced through a labor of love
   by past prolific thinkers and doing unto their work what they insist on doing
   to ours. And maybe that produces ingenuity? I don't know but that sounds
   about right.

** [[./wiki/admin/tools.org][Tool]]
