* Hi!
  My name is *Salvador Guzman* and this is my wiki :).
** What is this and Who am I?
   I'm a very active guy. I don't mean physically since I spent the majority of
   my day sitting on my triple-decker seat cushions. No, no. I am athletic in a
   in a more intellectual sense. I'm one of those too-smart for their own good
   type of people. This leads to the unfortunate scenario where I brainstorm
   more ideas than I know what to do with.

   This sounds like a brag but I swear its not. In fact, it is a curse. I am
   forced for time evermore to produce half-baked ideas that I cannot possibly
   refine on my own. Why not? Well, refining ideas gets in the way of generating
   more ideas! Isn't that sad? I think it is.

   Whatever potent combination nature sought out to imbue my mental headspace
   with suffers from an abudance of creativity. I know because it lies on a hair
   trigger mechanism that requires very little stimulus to start chasing its own
   tail. Yes. Yes.
** Area of Research
*** Mathematics
**** Real Analysis
*** Computer Science
*** Politics
*** Library Science
*** Literature
*** Language
**** English
**** Spanish
***** Mexican Spanish
